name: Playwright Tests Manual
on: workflow_dispatch
  inputs:
    SUB_APP_URL:
      description: “Sub app URL”
      required: true
    MAIN_APP_URL:
      description: “Main app URL”
      required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: pnpm ci
    - name: Install Playwright Browsers
      run: pnpx playwright install --with-deps
    - name: Start services
      run: pnpm start:proxy
      env:
        SUB_APP_URL: ${{ inputs.SUB_APP_URL }}
        MAIN_APP_URL: ${{ inputs.MAIN_APP_URL }}
    - name: Run Playwright tests
      run: pnpx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
